name: Generate Datas

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Gerar animação Snake
      - name: Generate Snake GIF
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: lcspaiva87
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publicar no branch "output"
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
