name: Generate profile animations

on:
  schedule:
    - cron: '0 0,12 * * *'  # Meia-noite e meio-dia
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Precisamos de todo o histórico de commits

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Generate Pac‑Man SVG
        run: |
          git clone https://github.com/abozanona/pacman-contribution-graph.git
          cd pacman-contribution-graph
          npm install
          node index.js --username ${{ github.repository_owner }} --output ../dist/pacman.svg

      - name: Deploy to “output” branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
